<#
.SYNOPSIS
Starts DOSBox-X with the Lemmings 3D CD mounted and waits for its window.

.DESCRIPTION
Loads tools/original/lem3d.conf plus a generated config that mounts the C:
folder and the CD image (as D:, with CD audio), sets the capture folder and
then runs -Run (by default: start the game from the CD).

The game runs straight from the CD; SETUP.EXE only writes its settings to
C:\LM3D.CD\LM3D.CFG, which must exist (see docs/original-game-navigation.md).

.PARAMETER Run
Commands to run after mounting, one per array element. Default starts the
game. Pass @() to stay at the DOS prompt.

.PARAMETER WaitSeconds
Extra wait after the window appears (lets the game reach its first screen).

.PARAMETER SkipIntro
Skips the intro videos and ends on the main menu (about 20 s in total).
#>
param(
    [string[]]$Run = @('D:', 'L3D'),
    [int]$WaitSeconds = 0,
    [switch]$SkipIntro,
    [int]$IntroDelay = 8,
    [switch]$Force
)
. (Join-Path $PSScriptRoot 'Lem3dCommon.ps1')

if (Get-Lem3dProcess) {
    if (-not $Force) { throw 'DOSBox-X is already running. Use quit.ps1 first, or -Force to start another.' }
}
foreach ($p in @($Lem3dDosbox, $Lem3dCue)) {
    if (-not (Test-Path $p)) { throw "Not found: $p" }
}
New-Item -ItemType Directory -Force $Lem3dCDrive, $Lem3dShots | Out-Null

$gen = Join-Path ([IO.Path]::GetDirectoryName($Lem3dState)) 'openlem3d-dosbox-autoexec.conf'
$lines = @(
    '# Generated by tools/original/launch.ps1. Do not edit.',
    '[dosbox]',
    "captures = $Lem3dShots",
    '[autoexec]',
    '@ECHO OFF',
    "MOUNT C `"$Lem3dCDrive`"",
    "IMGMOUNT D `"$Lem3dCue`" -t iso"
) + $Run
Set-Content -Path $gen -Value $lines -Encoding ascii

$base = Join-Path $PSScriptRoot 'lem3d.conf'
$dbArgs = @('-conf', "`"$base`"", '-conf', "`"$gen`"", '-nopromptfolder')
$proc = Start-Process -FilePath $Lem3dDosbox -ArgumentList $dbArgs `
    -WorkingDirectory (Split-Path $Lem3dDosbox) -PassThru
@{ pid = $proc.Id; started = (Get-Date).ToString('o') } | ConvertTo-Json | Set-Content $Lem3dState

$deadline = (Get-Date).AddSeconds(20)
$h = [IntPtr]::Zero
while ((Get-Date) -lt $deadline) {
    Start-Sleep -Milliseconds 200
    $h = [Lem3dWin32]::FindMainWindow($proc.Id)
    if ($h -ne [IntPtr]::Zero) { break }
}
if ($h -eq [IntPtr]::Zero) { throw 'DOSBox-X window did not appear within 20 s.' }
if ($WaitSeconds -gt 0) { Start-Sleep -Seconds $WaitSeconds }
[Lem3dWin32]::Focus($h) | Out-Null
if ($SkipIntro) {
    # Esc skips from any intro clip to the main menu, but is ignored while the
    # game loads and between clips. On the menu itself Esc opens a quit
    # confirmation, which N dismisses (N is harmless elsewhere). So: repeat
    # Esc, N a few times; whatever the timing, it ends on the main menu.
    Start-Sleep -Seconds $IntroDelay
    $send = Join-Path $PSScriptRoot 'send.ps1'
    for ($i = 0; $i -lt 4; $i++) { & $send ESC 'wait:2000' N 'wait:1000' }
    # The confirmation can appear late; a final N closes it if it is up.
    & $send 'wait:1500' N 'wait:1000'
    $h = [Lem3dWin32]::FindMainWindow($proc.Id)
}
$r = [Lem3dWin32]::ClientRectOnScreen($h)
Write-Output ("DOSBox-X running: pid {0}, client area {1}x{2} at ({3},{4})" -f $proc.Id, $r[2], $r[3], $r[0], $r[1])
